FT9 new branch Check
HaMeCTHuK/controllers-films-users pull request #1
Opened 2023-12-04 21:07 UTC by HaMeCTHuK

2023-12-04 21:43 UTC, HaMeCTHuK commented
Первая отправка на проверку

2023-12-05 06:22 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Но есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2023-12-05 06:22 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/controller/BaseController.java
> +        if (storage.containsKey(data.getId())) {
Можно инвертировать условие, и тогда ветка `else` не понадобится, что снизит цикломатическую сложность кода.

https://en.wikipedia.org/wiki/Cyclomatic_complexity

2023-12-05 06:22 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/controller/FilmController.java
> +    @PutMapping() //"/{id}"
Обычно идентификатор делают отдельным полем (а именно добавляют в путь), тогда не потребуется заводить класс `BaseUnit`, а можно будет работать просто с двумя отдельными полями

2023-12-05 06:22 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/model/Film.java
> +    //@PositiveOrZero (message = "Не может быть <= 0")  (оставил специально для себя)
1. Для этого можно закоммитить две разные версии и не оставлять этот код в комментари
2. Не очень понятно зачем тебе это 
3. Можно подумать о том, что для `duration` использовать специальную абстракцию `java.time.Duration`

2023-12-05 06:22 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/model/BaseUnit.java
> +@EqualsAndHashCode(of = {"id"}) //для сравнения используем только поле id
А смысл?
У тебя в `BaseUnit` и нет других полей, дефолтные `equals` и `hashCode`, которые сгенерирует аннотация `Data` будет работать аналогично

2023-12-05 06:22 UTC, LexLippi commented on src/test/java/ru/java/practicum/filmorate/controller/FilmControllerTest.java
> +                .releaseDate(LocalDate.of(1791,11,12))
А почему есть тесты только на валидацию даты выпуска, а на остальные поля - нет?

2023-12-05 06:22 UTC, LexLippi commented on src/test/java/ru/java/practicum/filmorate/controller/UserControllerTest.java
> +                .name(null)
Вопрос аналогичный тому, что оставил в другом тестовом классе

2023-12-06 18:45 UTC, HaMeCTHuK commented on src/main/java/ru/java/practicum/filmorate/controller/FilmController.java
> +    @PutMapping() //"/{id}"
Привет! Подскажи пожалуйста. BaseUnit сделал с заделом на будущее, чтобы если добавятся еще одинаковые поля или сущности с одинаковыми полями сразу использовать тут. Я могу этот класс оставить или это считается ошибкой?

2023-12-06 18:48 UTC, HaMeCTHuK commented on src/main/java/ru/java/practicum/filmorate/model/Film.java
> +    //@PositiveOrZero (message = "Не может быть <= 0")  (оставил специально для себя)
Я оставил это для себя сугубо в личных тестах) посмотреть что как лучше работает))) т.к. в задании не указано, что поле duration должно быть типом duration, решил что удобнее будет int. Комментарий удалю))

2023-12-06 18:48 UTC, HaMeCTHuK commented on src/main/java/ru/java/practicum/filmorate/model/BaseUnit.java
> +@EqualsAndHashCode(of = {"id"}) //для сравнения используем только поле id
Это я тоже сделал с заделом на будующие) Удалить и переделать? Это будет считаться ошибкой?

2023-12-08 21:30 UTC, HaMeCTHuK commented on src/main/java/ru/java/practicum/filmorate/controller/BaseController.java
> +        if (storage.containsKey(data.getId())) {
Понял, спасибо. Исправил

2023-12-08 21:30 UTC, HaMeCTHuK commented on src/test/java/ru/java/practicum/filmorate/controller/FilmControllerTest.java
> +                .releaseDate(LocalDate.of(1791,11,12))
Тесты добавил

2023-12-09 07:58 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/controller/FilmController.java
> +    @PutMapping() //"/{id}"
Это не считается ошибкой

Но с большой вероятностью у тебя набор полей у сущностей сильно расползется, ты захочешь на них навешивать сильно разные проверки. Иногда под них даже заводят отдельные классы, называемые `value-object`, чтобы отделить `userId` от `filmId`, например.

Поэтому большого смысла в этом нет

2023-12-09 07:59 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2023-12-09 14:08 UTC, merged