FZ10 pull request 1
HaMeCTHuK/controllers-films-users pull request #2
Opened 2023-12-24 20:22 UTC by HaMeCTHuK

Доделал ФЗ10 Отправляю на реквест

2023-12-25 21:30 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2023-12-25 21:30 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/controller/BaseController.java
> +/*
Согласно принципу KISS лучше удалить этот класс, тем более, что его потом всегда можно будет восстановить

2023-12-25 21:30 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/service/AbstractService.java
> +        if (!getAll().contains(inMemoryBaseStorage.get(id))) {
Этот метод работает за `O(n)`, где `n` - количество элементов в коллекции. 
Хотелось бы в этом методе получить сложность `O(1)`

2023-12-25 21:30 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/service/AbstractService.java
> +        if (!getAll().contains(getData(data.getId()))) {
Аналогично тому, что написал ниже

2023-12-25 21:30 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/service/FilmService.java
> +        if (!inMemoryUserStorage.getAll().contains(user) || !inMemoryFilmStorage.getAll().contains(film)) {
Про это уже писал

2023-12-25 21:30 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/service/FilmService.java
> +        if (film == null || user == null) {
Чем отличается данная проверка от проверки ниже? 
И там, и там нет элемента в коллекции. Зачем дважды эти случаи обрабатывать?

2023-12-25 21:30 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/service/UserService.java
> +public class UserService extends AbstractService<User> {
Замечания аналогичные `FilmService`

2023-12-25 21:30 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/storage/memory/InMemoryBaseStorage.java
> +        storage.remove(data.getId(), data);
У этого метода хуже асимптотика и он бессмысленнен, так как если в словаре идентификатору соответствует более одного элемента, то он ничего не идентифицирует

2023-12-25 21:30 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/storage/memory/InMemoryFilmStorage.java
> +        if (!getAll().contains(get(filmId))) {
Проверка выполняется за `O(n)`, а мы хотим за `O(1)`

2023-12-25 21:30 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/storage/memory/InMemoryFilmStorage.java
> +        return film.getLikes().add(userId);
Плохо модифицировать коллекцию таким образом, это нарушает инкапсуляцию, необходимо завести метод добавления лайка в `Film` и там выполнять данное действие.

Плюс метод `getLikes()` должен возвращать копию списка, а не сам список лайков, чтобы не нарушать инкапсуляцию

2023-12-25 21:30 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/storage/memory/InMemoryFilmStorage.java
> +        boolean isRemoved = film.getLikes().remove(userId);
Аналогично тому, что написал выше

2023-12-25 21:30 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/storage/memory/InMemoryUserStorage.java
> +public class InMemoryUserStorage extends InMemoryBaseStorage<User> implements UserStorage {
Замечания аналогичные `InMemoryFilmStorage`

2023-12-27 07:37 UTC, LexLippi requested changes
Привет!

Неплохая работа, но осталось некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2023-12-27 07:37 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/controller/UserController.java
> +        log.info("Текущее количество пользователей: {}", userService.getAll().size());
Не стоит дважды вызывать один и тот же метод, лучше сохранить его результат в локальную переменную. Это повысит производительность нашего кода

2023-12-27 07:37 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/model/Film.java
> +    HashSet<Long> likes = new HashSet<>(); //для лайков
1. модификатора доступа не хватает
2. надо переопределить метод `get` для этого поля, чтобы возвращать копию коллекции, чтобы у нас не было возможности модифицировать ее без методов `getLikesCount`, `addNewLike`, `deleteLike`

2023-12-27 07:37 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/model/User.java
> +    private HashSet<Long> friends = new HashSet<>(); // для другов
Надо переопределить метод `get` для этого поля

2023-12-27 07:37 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/storage/memory/InMemoryBaseStorage.java
> +    public HashMap<Long, T> getAll() {
Здесь ты возвращаешь копию `HashMap`, что работает за `O(n)`. Это нормально, если нам метод нужен для получения всей коллекции, но это плохо, если мы хотим на нем делать проверки для одного элемента, так как получим сложность равную `O(n)`.

Чтобы этого избежать, необходимо работать с методом `get`. Там если элемент не найден по идентификатору, то мы получим `null` и на этом можем основать свои проверки, такой метод работает в среднем за `O(1)`

2023-12-27 07:47 UTC, HaMeCTHuK commented on src/main/java/ru/java/practicum/filmorate/controller/UserController.java
> +        log.info("Текущее количество пользователей: {}", userService.getAll().size());
Странно, но я не могу найти 18 строчки у себя в проекте...

2023-12-27 07:48 UTC, HaMeCTHuK commented on src/main/java/ru/java/practicum/filmorate/controller/UserController.java
> +        log.info("Текущее количество пользователей: {}", userService.getAll().size());
return super.getData(); она была у меня только в 9 спринте

2023-12-28 08:04 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Остались некоторые замечания, которые необходимо исправить!

Желаю удачи!

2023-12-28 08:04 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/controller/UserController.java
> +        log.info("Текущее количество пользователей: {}", userService.getAll().size());
Не знаю почему она попала под комментарий, возможно это баг гитхаба.

Но суть претензии быоа не в ней, а в строчке `userService.getAll()`, которую ты вызываешь дважды и ее сложность - `O(n), n - количество пользователей`, не стоит дважды ее вызывать в сервисе, надо просто сохранить ее результат в локальную переменную

2023-12-28 08:04 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/model/BaseUnit.java
> +    public abstract HashSet<Long> getClassSet();
Так лучше не делать. То, что у каждого класса с данными должен быть идентификатор - допустимая логика, но требовать какой-то метод, который возвращает `HashSet` чего-то, даже непонятно чего - это неправильно

2023-12-28 08:04 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/model/Film.java
> +    private HashSet<Long> likes = new HashSet<>(); //для лайков
Можно просто переопределить метод `public HashSet<Long> getLikes()`

2023-12-28 08:04 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/model/Film.java
> +    }
Очень странный метод

2023-12-28 08:04 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/model/User.java
> +    private HashSet<Long> friends = new HashSet<>(); // для другов
Аналогично тому, что написал про `likes`

2023-12-28 08:04 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/service/UserService.java
> +        } else if (user == null) {
`else` не нужно, так как ты выбрасываешь исключение в условном операторе

2023-12-28 08:04 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/service/UserService.java
> +        User user = getData(userId);
Стоит сначала сделать проверку на `null` и только потом кидать запрос к храниилище. Зачем обращаться  к нему лишний раз?

2023-12-28 08:04 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/service/AbstractService.java
> +       for (Long id : inMemoryBaseStorage.getAll())  {
Зачем перекладывать из одного списка в другой?

2023-12-28 08:04 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/storage/memory/InMemoryBaseStorage.java
> +    public List<Long> getAll() {
Может лучше вернуть `List<T>`?

```
return new ArrayList<>(storage.values());
```

2023-12-28 14:15 UTC, HaMeCTHuK commented
Постарался исправить все методы. Спасибо большое за терпение, что проверяешь мой кривой код. Отправляю еще на проверку)))

2023-12-29 08:14 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-01-03 09:08 UTC, merged