Add database
HaMeCTHuK/controllers-films-users pull request #4
Opened 2024-01-19 09:40 UTC by HaMeCTHuK

Send branch to check

2024-01-20 10:00 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые надо исправить!

Желаю удачи!

2024-01-20 10:00 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/model/Genre.java
> +    String name;
Стоит добавить модификатор доступа `private`

2024-01-20 10:00 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/model/Mpa.java
> +    String name;
Стоит добавить модификатор доступа `private`

2024-01-20 10:00 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/service/AbstractService.java
> +        if (abstractStorage.get(id) == null) {
Делаем два запроса в базу данных. Это плохо с точки зрения производительности

2024-01-20 10:00 UTC, LexLippi commented on src/main/java/ru/java/practicum/filmorate/service/AbstractService.java
> +        if (abstractStorage.get(data.getId()) == null) {
Лучше не делать `get`, а потом `update`, СУБД умеет возвращать количество измененных строк и таким образом уже после обновления можно понять было оно успешно или нет, не совершая лишний запрос к СУБД

2024-01-20 10:00 UTC, LexLippi commented on src/main/resources/schema.sql
> +  rating_name   VARCHAR(255)
`not null`

2024-01-20 10:00 UTC, LexLippi commented on src/main/resources/schema.sql
> +  genre_name    VARCHAR(255)
`not null`

2024-01-20 10:00 UTC, LexLippi commented on src/main/resources/schema.sql
> +  mpa_rating_id INT REFERENCES MPARating(id)
`not null`

2024-01-21 08:12 UTC, HaMeCTHuK commented on src/main/java/ru/java/practicum/filmorate/model/Genre.java
> +    String name;
Вечная проблема моя))) Добавил)

2024-01-21 08:12 UTC, HaMeCTHuK commented on src/main/java/ru/java/practicum/filmorate/model/Mpa.java
> +    String name;
Добавил)

2024-01-21 08:12 UTC, HaMeCTHuK commented on src/main/java/ru/java/practicum/filmorate/service/AbstractService.java
> +        if (abstractStorage.get(id) == null) {
Изменил метод

2024-01-21 08:13 UTC, HaMeCTHuK commented on src/main/java/ru/java/practicum/filmorate/service/AbstractService.java
> +        if (abstractStorage.get(data.getId()) == null) {
Ошибку понял, постарался исправить, спасибо

2024-01-21 08:13 UTC, HaMeCTHuK commented on src/main/resources/schema.sql
> +  rating_name   VARCHAR(255)
Исправил)

2024-01-21 08:13 UTC, HaMeCTHuK commented on src/main/resources/schema.sql
> +  genre_name    VARCHAR(255)
Исправил)

2024-01-22 07:49 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-01-28 10:29 UTC, merged